#!/bin/bash

# stops processing in case of failure
set -euo pipefail

# prints each line executed
set -x

pwd

echo "Your solution goes here"

nft_conf='/etc/nftables.conf'
sudo sed -i /"DROPPING PACKET"/d $nft_conf
sudo systemctl restart nftables

sudo nft add rule inet filter input ip saddr 129.132.121.162 tcp dport 5432 accept
sudo nft add rule inet filter input tcp dport 5432 reject

sudo sed -i 's/location \/app/location \/app\//' /etc/nginx/sites-enabled/company-app.conf
sudo systemctl restart nginx

sudo apt update -y
sudo apt install -y snapd
sudo snap install core; sudo snap refresh core
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
sudo certbot --server http://acme.dtf.netsec.inf.ethz.ch/acme/default/directory --register-unsafely-without-email --noninteractive -d lhoffman.student.dtf.netsec.inf.ethz.ch --agree-tos
