#!/bin/bash

# stops processing in case of failure
set -euo pipefail

# prints each line executed
set -x

pwd

echo "Your solution goes here"

nft_conf='/etc/nftables.conf'
sed -i /"DROPPING PACKET"/d $nft_conf
sudo systemctl restart nftables

nft add rule inet filter input ip saddr 129.132.121.162 tcp dport 5432 accept
